"""Research-only prospective cash-merger shadow ledger and decision engine."""

from .cash_rate import FredDtb3RateSource, ObservedCashRate
from .edgar import (
    EdgarEventSource,
    EdgarFiling,
    EdgarGateway,
    EdgarSourceError,
    EdgarToolsGateway,
    IssuerIdentity,
    SourceRefresh,
    SourceReview,
)
from .ledger import (
    EventObservation,
    EventStatus,
    LedgerWrite,
    ShadowLedger,
    ShadowQualification,
)
from .market import (
    AegisCatalogMarkSource,
    MarketMarkBatch,
    MarketUnavailable,
)
from .selection import (
    CashMergerSelector,
    CompletionCase,
    CompletionForecast,
    CompletionSelectionEngine,
    EngineCausalityError,
    EngineCoverageError,
    EngineIdentityError,
    EngineProbabilityError,
    EngineRankingError,
    MarketImpliedSelectionEngine,
    MarketMark,
    SelectionAssessment,
    SelectionAuthority,
    SelectionEngineIdentity,
    SelectionError,
    SelectionExclusion,
    SelectionExclusionReason,
    SelectionResult,
    ShadowDecision,
    ShadowPosition,
)
from .shadow import (
    CashMergerShadow,
    ShadowEventSource,
    ShadowEvidenceError,
    ShadowMarkSource,
    ShadowRunEvidence,
)

__all__ = [
    "AegisCatalogMarkSource",
    "CashMergerSelector",
    "CashMergerShadow",
    "CompletionCase",
    "CompletionForecast",
    "CompletionSelectionEngine",
    "EdgarEventSource",
    "EdgarFiling",
    "EdgarGateway",
    "EdgarSourceError",
    "EdgarToolsGateway",
    "EngineCausalityError",
    "EngineCoverageError",
    "EngineIdentityError",
    "EngineProbabilityError",
    "EngineRankingError",
    "EventObservation",
    "EventStatus",
    "FredDtb3RateSource",
    "IssuerIdentity",
    "LedgerWrite",
    "MarketImpliedSelectionEngine",
    "MarketMark",
    "MarketMarkBatch",
    "MarketUnavailable",
    "ObservedCashRate",
    "SelectionAssessment",
    "SelectionAuthority",
    "SelectionEngineIdentity",
    "SelectionError",
    "SelectionExclusion",
    "SelectionExclusionReason",
    "SelectionResult",
    "ShadowDecision",
    "ShadowEventSource",
    "ShadowEvidenceError",
    "ShadowLedger",
    "ShadowMarkSource",
    "ShadowPosition",
    "ShadowQualification",
    "ShadowRunEvidence",
    "SourceRefresh",
    "SourceReview",
]
