from __future__ import annotations

from research.aegis_research.configuration.resolution import (
    ResolvedRunConfig,
    load_run_config,
    resolve_run_config,
    with_run_config_selection,
)
from research.aegis_research.configuration.schema import (
    CONFIG_SCHEMA_VERSION,
    DATA_ARRAY_SHORTCUTS,
    DATA_QUALITY_DEGRADATIONS,
    DENIED_PASSTHROUGH_KEYS,
    EXPERIMENT_NAME_RE,
    FORWARD_OPTIMIZATION_REQUIRED_MESSAGE,
    MISSING_POLICIES,
    OHLCV_ARRAYS,
    OPTIMIZATION_RETURN_GRID_POLICIES,
    OPTIMIZATION_SEARCH_POLICIES,
    PORTFOLIO_DIRECTIONS,
    PORTFOLIO_TARGET_SIZE_TYPES,
    RANKING_DIRECTIONS,
    RUN_EXECUTABLE_DENIED_KEYS,
    SECRET_KEY_RE,
    SECRET_VALUE_RE,
    SIGNAL_EXECUTION_TIMINGS,
    SIGNAL_POLICIES,
    ConfigSelectionEvidence,
    ConfigValidationError,
    ConfigValidationIssue,
    DataConfig,
    DataQualityConfig,
    OptimizationConfig,
    OptimizationEvidenceConfig,
    PortfolioConfig,
    RankingConfig,
    ReportConfig,
    RunConfig,
    RunIndicatorSourceConfig,
    RunSourceRefConfig,
    RunSplitConfig,
    SignalConfig,
    expand_data_arrays,
)
from research.aegis_research.configuration.secrets import (
    known_config_secret_values,
    redact_config,
    redact_text,
    resolve_secret_refs,
    to_builtin,
)
from research.aegis_research.market_data.sources import (
    LOCAL_DATA_SOURCES,
    data_sources,
    remote_data_sources,
)

DATA_SOURCES = data_sources()
REMOTE_DATA_SOURCES = remote_data_sources()

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "DATA_ARRAY_SHORTCUTS",
    "DATA_QUALITY_DEGRADATIONS",
    "DATA_SOURCES",
    "DENIED_PASSTHROUGH_KEYS",
    "EXPERIMENT_NAME_RE",
    "FORWARD_OPTIMIZATION_REQUIRED_MESSAGE",
    "LOCAL_DATA_SOURCES",
    "MISSING_POLICIES",
    "OHLCV_ARRAYS",
    "OPTIMIZATION_RETURN_GRID_POLICIES",
    "OPTIMIZATION_SEARCH_POLICIES",
    "PORTFOLIO_DIRECTIONS",
    "PORTFOLIO_TARGET_SIZE_TYPES",
    "RANKING_DIRECTIONS",
    "REMOTE_DATA_SOURCES",
    "RUN_EXECUTABLE_DENIED_KEYS",
    "SECRET_KEY_RE",
    "SECRET_VALUE_RE",
    "SIGNAL_EXECUTION_TIMINGS",
    "SIGNAL_POLICIES",
    "ConfigSelectionEvidence",
    "ConfigValidationError",
    "ConfigValidationIssue",
    "DataConfig",
    "DataQualityConfig",
    "OptimizationConfig",
    "OptimizationEvidenceConfig",
    "PortfolioConfig",
    "RankingConfig",
    "ReportConfig",
    "ResolvedRunConfig",
    "RunConfig",
    "RunIndicatorSourceConfig",
    "RunSourceRefConfig",
    "RunSplitConfig",
    "SignalConfig",
    "expand_data_arrays",
    "known_config_secret_values",
    "load_run_config",
    "redact_config",
    "redact_text",
    "resolve_run_config",
    "resolve_secret_refs",
    "to_builtin",
    "with_run_config_selection",
]
