"""Public config surface — single import home for all configuration names.

All public configuration types, constants, and entry points are re-exported
here. Internal implementation modules are package-private.
"""

from research.aegis_research.canonical_json import to_builtin
from research.aegis_research.configuration.resolution import (
    ResolvedRunConfig,
    load_run_config,
    resolve_run_config,
    with_run_config_selection,
)
from research.aegis_research.configuration.schema import (
    CONFIG_SCHEMA_VERSION,
    DATA_ARRAY_SHORTCUTS,
    DEFAULT_LOCK_ROLE,
    FORWARD_OPTIMIZATION_REQUIRED_MESSAGE,
    LOCK_ROLES,
    MISSING_POLICIES,
    OHLCV_ARRAYS,
    OPTIMIZATION_SEARCH_POLICIES,
    PORTFOLIO_DIRECTIONS,
    PREPASS_CONST_FIELDS,
    PREPASS_REQUIRED_FIELDS,
    SIGNAL_EXECUTION_TIMINGS,
    SIGNAL_POLICIES,
    ConfigSelectionEvidence,
    ConfigValidationError,
    ConfigValidationIssue,
    DataConfig,
    InstrumentBandConfig,
    Lock,
    OptimizationConfig,
    PortfolioConfig,
    RankingConfig,
    ReportConfig,
    RunConfig,
    RunIndicatorSourceConfig,
    RunSourceRefConfig,
    SignalConfig,
    expand_data_arrays,
    lock_handle,
    merge_data_arrays,
)

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "DATA_ARRAY_SHORTCUTS",
    "DEFAULT_LOCK_ROLE",
    "FORWARD_OPTIMIZATION_REQUIRED_MESSAGE",
    "LOCK_ROLES",
    "MISSING_POLICIES",
    "OHLCV_ARRAYS",
    "OPTIMIZATION_SEARCH_POLICIES",
    "PORTFOLIO_DIRECTIONS",
    "PREPASS_CONST_FIELDS",
    "PREPASS_REQUIRED_FIELDS",
    "SIGNAL_EXECUTION_TIMINGS",
    "SIGNAL_POLICIES",
    "ConfigSelectionEvidence",
    "ConfigValidationError",
    "ConfigValidationIssue",
    "DataConfig",
    "InstrumentBandConfig",
    "Lock",
    "OptimizationConfig",
    "PortfolioConfig",
    "RankingConfig",
    "ReportConfig",
    "ResolvedRunConfig",
    "RunConfig",
    "RunIndicatorSourceConfig",
    "RunSourceRefConfig",
    "SignalConfig",
    "expand_data_arrays",
    "load_run_config",
    "lock_handle",
    "merge_data_arrays",
    "resolve_run_config",
    "to_builtin",
    "with_run_config_selection",
]
